version: '2'
services:
  app:
    build: .
    command: [bundle, exec, puma, -C, config/puma.rb]
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.app.{{.ID}}"
    depends_on:
      - fluentd
  fluentd:
    build: ./containers/fluentd
    env_file: .env
    ports:
      - "24224:24224"
  nginx:
    build: ./containers/nginx
    ports:
      - "8080:80"
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        tag: "docker.nginx.{{.ID}}"
    depends_on:
      - fluentd
      - app
